title: "nucofu"
author: "Rustu Judika Rahmat"
description: "Catatan kecil eksperimen saya di linux dan analisis data aktivitas yang terjadi di internet. Kadang serius, kadang cuma sekedar dokumentasi."
permalink: /:title/
lang: "id"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {url: "/posts", title: "Posts", sidebaricon: mail-bulk}
  - {file: "shelf.html", sidebaricon: bookmark}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

footer:
  - {title: Instagram, icon: instagram, url: "https://instagram.com/nullcolorfull/"}
  - {title: Mail, icon: envelope, url: "mailto:rusjud1ka@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/nucofu/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

pagination:
  enabled: true
  offset: 0 # starting point of page
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0 # limit of pages, 0 mean all pages
  per_page: 1
  sort_field: 'date'
  sort_reverse: true

plugins:
 - jekyll-feed
 - jekyll-paginate-v2
